###
GET http://localhost:3000/productlist/

###
DELETE http://localhost:3000/productlist/625d3f91dd25d90a34433d7b

###
POST http://localhost:3000/productlist
Content-Type: application/json

{
    "name": "Samsung Galaxy s15",
    "price": 1666,
    "description": "It's good Samsung s15"
}

###
PATCH http://localhost:3000/productlist/625d3f91dd25d90a34433d7b
Content-Type: application/json

{
    "name": "Apple airpods",
    "price": 5020,
    "description": "It's good updated Apple" 
}